name: zen_circuit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_in_app_messaging: ^0.8.1+5
  firebase_messaging: ^15.2.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_translation: ^0.20.1
  intl_utils: ^2.8.8
  cloud_firestore: ^5.6.6
  just_audio: ^0.10.2
  fl_chart: ^0.71.0
  flutter_launcher_icons: ^0.14.3
  just_audio_background: ^0.0.1-beta.16
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/help/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"